version: "3"

services:
  sb-image:
    build: .
    ports:
      - "5000:5000"
    
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    
    environment:
      - PORT=5000
  

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: sbadmin
      MONGO_INITDB_ROOT_PASSWORD: sbadmin1234
    
    volumes:
      - mongo-db:/data/db

volumes:
  mongo-db: